# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8080

# ==============================================================
# CONFIGURACIÓN DEL CORE BANCARIO (POSTGRESQL LOCAL - ON PREMISE)
# ==============================================================
# 1. Conexión a la base de datos local (Reemplazamos Supabase por localhost)
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_core_FinancieraConfianza

# Tu usuario local (por defecto al instalar PostgreSQL siempre es postgres)
spring.datasource.username=postgres

# AQUÍ PON LA CONTRASEÑA QUE CREASTE AL INSTALAR POSTGRESQL EN TU PC
spring.datasource.password=12345678

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# 'update' creará o actualizará las tablas automáticamente en tu bd_core_financiero
spring.jpa.hibernate.ddl-auto=update
# Esto imprimirá en la consola las consultas SQL que hace Spring Boot
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect