# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=${PORT:8080}

# ==============================================================
# CONFIGURACION RENDER / POSTGRESQL EN LA NUBE
# ==============================================================
spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion local de referencia:
# spring.datasource.url=jdbc:postgresql://localhost:5432/bd_core_FinancieraConfianza
# spring.datasource.username=postgres
# spring.datasource.password=12345678

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tasa moratoria diaria utilizada en el prototipo: 0.05 %
financiera.mora.tasa-diaria=0.0005
